spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./target/h2-db/challenge;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  address: localhost
  port: 8080

logging:
  level:
    liquibase: INFO
